### ISSUE TITLE
failed unit tests

### ISSUE THREAD

**Issue by donghwan-shin** [SepShr/MLCSHE#35]
### Input

```bash
(venv) ➜  MLCSHE git:(Dev-Sepehr) $ python -m unittest
```

### Output

```bash
EEE...../Users/donghwan.shin/Repositories/MLCSHE/venv/lib/python3.9/site-packages/deap/creator.py:138: RuntimeWarning: A class named 'FitnessMin' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  warnings.warn("A class named '{0}' has already been created and it "
/Users/donghwan.shin/Repositories/MLCSHE/venv/lib/python3.9/site-packages/deap/creator.py:138: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  warnings.warn("A class named '{0}' has already been created and it "
.s.EE....EEE.EE/Users/donghwan.shin/Repositories/MLCSHE/venv/lib/python3.9/site-packages/deap/creator.py:138: RuntimeWarning: A class named 'Scenario' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  warnings.warn("A class named '{0}' has already been created and it "
EsEEEEEE.
======================================================================
ERROR: test_breed_scenario_testInput1 (tests.test_breed_scenario.TestBreedScenario)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_breed_scenario.py", line 13, in test_breed_scenario_testInput1
    enumLimits=problem.enumLimits
AttributeError: module 'problem' has no attribute 'enumLimits'

======================================================================
ERROR: tests.test_calculate_cdist (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_calculate_cdist
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_calculate_cdist.py", line 3, in <module>
    from src.utils.PairwiseDistance import PairwiseDistance
  File "/Users/donghwan.shin/Repositories/MLCSHE/src/utils/PairwiseDistance.py", line 2, in <module>
    from scipy.spatial.distance import cdist, pdist, squareform
ModuleNotFoundError: No module named 'scipy'


======================================================================
ERROR: tests.test_calculate_pdist (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_calculate_pdist
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_calculate_pdist.py", line 5, in <module>
    from src.utils.PairwiseDistance import PairwiseDistance
  File "/Users/donghwan.shin/Repositories/MLCSHE/src/utils/PairwiseDistance.py", line 2, in <module>
    from scipy.spatial.distance import cdist, pdist, squareform
ModuleNotFoundError: No module named 'scipy'


======================================================================
ERROR: tests.test_fitness_function (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_fitness_function
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_fitness_function.py", line 5, in <module>
    from src.utils.PairwiseDistance import PairwiseDistance
  File "/Users/donghwan.shin/Repositories/MLCSHE/src/utils/PairwiseDistance.py", line 2, in <module>
    from scipy.spatial.distance import cdist, pdist, squareform
ModuleNotFoundError: No module named 'scipy'


======================================================================
ERROR: test_flatten_testInput1 (tests.test_flatten.TestFlatten)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_flatten.py", line 13, in test_flatten_testInput1
    enumLimits=problem.enumLimits
AttributeError: module 'problem' has no attribute 'enumLimits'

======================================================================
ERROR: test_individual_in_list_testInput1 (tests.test_individual_in_list.TestIndividualInList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_individual_in_list.py", line 13, in test_individual_in_list_testInput1
    enumLimits=problem.enumLimits
AttributeError: module 'problem' has no attribute 'enumLimits'

======================================================================
ERROR: test_initialize_hetero_vector_testInput1 (tests.test_initialize_hetero_vector.TestInitializeHeteroVector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_initialize_hetero_vector.py", line 11, in test_initialize_hetero_vector_testInput1
    scenario = initialize_hetero_vector(c, lmt)
  File "/Users/donghwan.shin/Repositories/MLCSHE/src/utils/utility.py", line 36, in initialize_hetero_vector
    for i in range(0, len(limits)):
TypeError: object of type 'type' has no len()

======================================================================
ERROR: test_is_similar_testInput1 (tests.test_is_similar.TestIsSimilar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_is_similar.py", line 13, in test_is_similar_testInput1
    enumLimits=problem.enumLimits
AttributeError: module 'problem' has no attribute 'enumLimits'

======================================================================
ERROR: test_mutate_scenario_testInput1 (tests.test_mutate_scenario.TestMutateScenario)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_mutate_scenario.py", line 13, in test_mutate_scenario_testInput1
    enumLimits=problem.enumLimits
AttributeError: module 'problem' has no attribute 'enumLimits'

======================================================================
ERROR: test_prepare_for_distance_evaluation_testInput1 (tests.test_prepare_for_distance_evaluation.TestPrepareForDistanceEvaluation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_prepare_for_distance_evaluation.py", line 12, in test_prepare_for_distance_evaluation_testInput1
    enumLimits=problem.enumLimits
AttributeError: module 'problem' has no attribute 'enumLimits'

======================================================================
ERROR: test_translate_scenario_list_testInput1 (tests.test_translate_scenario_list.TestTranslateScenarioList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_translate_scenario_list.py", line 15, in test_translate_scenario_list_testInput1
    translated_scenario_list = translate_scenario_list(scenario_list)
  File "/Users/donghwan.shin/Repositories/MLCSHE/simulation_utils.py", line 114, in translate_scenario_list
    road_flag = get_road(scenario_list, road_flag)
  File "/Users/donghwan.shin/Repositories/MLCSHE/simulation_utils.py", line 467, in get_road
    if fv[3] == 0:  # straight Road
IndexError: list index out of range

======================================================================
ERROR: test_update_archive_best_random_testInput1 (tests.test_update_archive_best_random.TestUpdateArchiveBestRandom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_update_archive_best_random.py", line 14, in test_update_archive_best_random_testInput1
    enumLimits=problem.enumLimits
AttributeError: module 'problem' has no attribute 'enumLimits'

======================================================================
ERROR: test_update_archive_diverse_best_random_testInput1 (tests.test_update_archive_diverse_best_random.TestUpdateArchiveDiverseBestRandom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_update_archive_diverse_best_random.py", line 14, in test_update_archive_diverse_best_random_testInput1
    enumLimits=problem.enumLimits
AttributeError: module 'problem' has no attribute 'enumLimits'

======================================================================
ERROR: test_update_archive_diverse_elitist_testInput1 (tests.test_update_archive_diverse_elitist.TestUpdateArchiveDiverseElitist)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_update_archive_diverse_elitist.py", line 14, in test_update_archive_diverse_elitist_testInput1
    enumLimits=problem.enumLimits
AttributeError: module 'problem' has no attribute 'enumLimits'

======================================================================
ERROR: test_update_archive_diverse_random_testInput1 (tests.test_update_archive_diverse_random.TestUpdateArchiveDiverseRandom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_update_archive_diverse_random.py", line 14, in test_update_archive_diverse_random_testInput1
    enumLimits=problem.enumLimits
AttributeError: module 'problem' has no attribute 'enumLimits'

======================================================================
ERROR: test_update_archive_elitist_testInput1 (tests.test_update_archive_elitist.TestUpdateArchiveElitist)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_update_archive_elitist.py", line 14, in test_update_archive_elitist_testInput1
    enumLimits=problem.enumLimits
AttributeError: module 'problem' has no attribute 'enumLimits'

======================================================================
ERROR: test_update_archive_random_testInput1 (tests.test_update_archive_random.TestUpdateArchiveElitist)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/MLCSHE/tests/test_update_archive_random.py", line 14, in test_update_archive_random_testInput1
    enumLimits=problem.enumLimits
AttributeError: module 'problem' has no attribute 'enumLimits'

----------------------------------------------------------------------
Ran 32 tests in 0.007s

FAILED (errors=17, skipped=2)
[[0, 2, 1, 2, 0, 1, 1, 0, 5.0, 352.5, 102.0, 176.6, 253.9, 396.3, 3.7, 57.1, 509.2, 590.0], [0, 2, 1, 2, 0, 1, 1, 1, 253.2, 466.0, 638.3, 478.1, 800.0, 599.5, 747.6, 800.0, 166.4, 301.3], [2, 6, 0, 3, 2, 0, 0, 0, 5.0, 352.5, 102.0, 176.6, 253.9, 396.3, 3.7, 57.1, 509.2, 590.0], [2, 6, 0, 3, 2, 0, 0, 1, 253.2, 466.0, 638.3, 478.1, 800.0, 599.5, 747.6, 800.0, 166.4, 301.3]]

```

### Note

1. It's better to fix any broken test cases (e.g., due to an update on the code) before they are pushed to the remote.
2. For outdated tests, it's okay to comment out temporarily (although properly fixing them would be the best)
3. Some errors happen simply because `requirements.txt` does not include `scipy` ;-)

**Comment by SepShr** [comment]
Commit aa7bcc34e9dd40ae695731e0e3444bad0a4829f1 fixes all the problems related to this issue.
