### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by donghwan-shin** [SepShr/MLCSHE#44]
### Issue 1
Input:
```zsh
nvidia-docker exec -i -t pylot /home/erdos/workspace/pylot/scripts/run_simulator.sh
```
Output:
```zsh
Error: No such container: pylot
```

### Issue 2
Input (after installing everything):
```zsh
python run_random_search.py 30
```
Output:
```zsh
Traceback (most recent call last):
  File "/home/donghwan/Repositories/MLCSHE/run_random_search.py", line 17, in <module>
    from pylot.RandomSearch import RandomSearch
  File "/home/donghwan/Repositories/MLCSHE/pylot/RandomSearch.py", line 17, in <module>
    from simulation_manager_cluster import (ContainerSimManager,
  File "/home/donghwan/Repositories/MLCSHE/simulation_manager_cluster.py", line 9, in <module>
    import docker
ModuleNotFoundError: No module named 'docker'
```
Output (after running `pip install docker`):
```zsh
(venv) (base) ➜  MLCSHE git:(Dev-Sepehr) python run_random_search.py 30
Traceback (most recent call last):
  File "/home/donghwan/Repositories/MLCSHE/run_random_search.py", line 49, in <module>
    main(args.sim_budget)
  File "/home/donghwan/Repositories/MLCSHE/run_random_search.py", line 37, in main
    random_search = RandomSearch(scen_enumLimits=cfg.scenario_enumLimits, radius=cfg.region_radius,
  File "/home/donghwan/Repositories/MLCSHE/pylot/RandomSearch.py", line 61, in __init__
    self.ff_target_prob = cfg.finess_function_target_probability
AttributeError: module 'pylot.search_config' has no attribute 'finess_function_target_probability'
```

**Comment by SepShr** [comment]
Commit 7dc89bcc50698a46c940622ac547e29067024d65 addressed the above issues.

Please let me know if there are other issues to be addressed. Thanks!

**Comment by donghwan-shin** [comment]
on the updated version, when I executed pylot using the following commands (line by line):
```
nvidia-docker exec -i -t pylot /bin/bash
cd workspace/pylot/
python3 pylot.py --flagfile=configs/detection.conf
```
I got the following error:
```
Traceback (most recent call last):
  File "<string>", line 31, in <module>
  File "/home/erdos/workspace/pylot/pylot/perception/detection/detection_operator.py", line 89, in __init__
    with open(self._flags.mlco_list_path, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
ERROR: CARLA version 784d9b9f is not supported; assuming this is version 0.9.10
```
but it does not halt. It's still running without printing any new lines for around 10 mins. I am unsure if this is the correct behaviour. 

FYI, on the terminal where I executed the docker image, I have the following messages:
```
(venv) (base) ➜  MLCSHE git:(Dev-Sepehr) nvidia-docker exec -i -t pylot /home/erdos/workspace/pylot/scripts/run_simulator.sh
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
sh: 1: xdg-user-dir: not found
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default

```

**Comment by SepShr** [comment]
I think I'll remove the sanity check steps. I remembered, after seeing the above error, that the pylot source code is changed to a degree that the usual pylot obstacle detection might not work easily.

Regarding the terminal output, it seems that you GPU is not recognized. I'll update the INSTALL.md further to fix it.

**Comment by SepShr** [comment]
Commit b8bf685a970af3437222fc42f9413642c6178dd5 has the necessary updates: removed sanity check. Added a way to monitor gpu and search execution.

Please let me know if there are other problems. Thanks.

**Comment by donghwan-shin** [comment]
Okay, it turned out that the error `ALSA lib confmisc.c:767:(parse_card) cannot find card '0'` is about the sound card. Anyway, it seems fine now. Thanks.
